classdef Arm_KinovaPoseFeedback < robotics.ros.Message
    %Arm_KinovaPoseFeedback MATLAB implementation of kinova_msgs/Arm_KinovaPoseFeedback
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2019 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'kinova_msgs/Arm_KinovaPoseFeedback' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'a3d0acc7643d70196e513c76ce4fd6d9' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        KinovaMsgsKinovaPoseClass = robotics.ros.msg.internal.MessageFactory.getClassForType('kinova_msgs/KinovaPose') % Dispatch to MATLAB class for message type kinova_msgs/KinovaPose
    end
    
    properties (Dependent)
        KinovaPose
    end
    
    properties (Access = protected)
        Cache = struct('KinovaPose', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'KinovaPose'} % List of non-constant message properties
        ROSPropertyList = {'kinova_pose'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = Arm_KinovaPoseFeedback(msg)
            %Arm_KinovaPoseFeedback Construct the message object Arm_KinovaPoseFeedback
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function kinovapose = get.KinovaPose(obj)
            %get.KinovaPose Get the value for property KinovaPose
            if isempty(obj.Cache.KinovaPose)
                obj.Cache.KinovaPose = feval(obj.KinovaMsgsKinovaPoseClass, obj.JavaMessage.getKinovaPose);
            end
            kinovapose = obj.Cache.KinovaPose;
        end
        
        function set.KinovaPose(obj, kinovapose)
            %set.KinovaPose Set the value for property KinovaPose
            validateattributes(kinovapose, {obj.KinovaMsgsKinovaPoseClass}, {'nonempty', 'scalar'}, 'Arm_KinovaPoseFeedback', 'KinovaPose');
            
            obj.JavaMessage.setKinovaPose(kinovapose.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.KinovaPose)
                obj.Cache.KinovaPose.setJavaObject(kinovapose.getJavaObject);
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.KinovaPose = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Recursively copy compound properties
            cpObj.KinovaPose = copy(obj.KinovaPose);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.KinovaPose = feval([obj.KinovaMsgsKinovaPoseClass '.loadobj'], strObj.KinovaPose);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.KinovaPose = saveobj(obj.KinovaPose);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.kinova_msgs.Arm_KinovaPoseFeedback.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.kinova_msgs.Arm_KinovaPoseFeedback;
            obj.reload(strObj);
        end
    end
end
