classdef FingerPosition < robotics.ros.Message
    %FingerPosition MATLAB implementation of kinova_msgs/FingerPosition
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2019 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'kinova_msgs/FingerPosition' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'f56891e5dcd1900989f764a9b845c8e5' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        Finger1
        Finger2
        Finger3
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Finger1', 'Finger2', 'Finger3'} % List of non-constant message properties
        ROSPropertyList = {'finger1', 'finger2', 'finger3'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = FingerPosition(msg)
            %FingerPosition Construct the message object FingerPosition
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function finger1 = get.Finger1(obj)
            %get.Finger1 Get the value for property Finger1
            finger1 = single(obj.JavaMessage.getFinger1);
        end
        
        function set.Finger1(obj, finger1)
            %set.Finger1 Set the value for property Finger1
            validateattributes(finger1, {'numeric'}, {'nonempty', 'scalar'}, 'FingerPosition', 'Finger1');
            
            obj.JavaMessage.setFinger1(finger1);
        end
        
        function finger2 = get.Finger2(obj)
            %get.Finger2 Get the value for property Finger2
            finger2 = single(obj.JavaMessage.getFinger2);
        end
        
        function set.Finger2(obj, finger2)
            %set.Finger2 Set the value for property Finger2
            validateattributes(finger2, {'numeric'}, {'nonempty', 'scalar'}, 'FingerPosition', 'Finger2');
            
            obj.JavaMessage.setFinger2(finger2);
        end
        
        function finger3 = get.Finger3(obj)
            %get.Finger3 Get the value for property Finger3
            finger3 = single(obj.JavaMessage.getFinger3);
        end
        
        function set.Finger3(obj, finger3)
            %set.Finger3 Set the value for property Finger3
            validateattributes(finger3, {'numeric'}, {'nonempty', 'scalar'}, 'FingerPosition', 'Finger3');
            
            obj.JavaMessage.setFinger3(finger3);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Finger1 = obj.Finger1;
            cpObj.Finger2 = obj.Finger2;
            cpObj.Finger3 = obj.Finger3;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Finger1 = strObj.Finger1;
            obj.Finger2 = strObj.Finger2;
            obj.Finger3 = strObj.Finger3;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Finger1 = obj.Finger1;
            strObj.Finger2 = obj.Finger2;
            strObj.Finger3 = obj.Finger3;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.kinova_msgs.FingerPosition.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.kinova_msgs.FingerPosition;
            obj.reload(strObj);
        end
    end
end
