classdef SetEndEffectorOffsetRequest < robotics.ros.Message
    %SetEndEffectorOffsetRequest MATLAB implementation of kinova_msgs/SetEndEffectorOffsetRequest
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2019 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'kinova_msgs/SetEndEffectorOffsetRequest' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '7a5c04366489f137e01b31118dcce900' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        GeometryMsgsVector3Class = robotics.ros.msg.internal.MessageFactory.getClassForType('geometry_msgs/Vector3') % Dispatch to MATLAB class for message type geometry_msgs/Vector3
    end
    
    properties (Dependent)
        Status
        Offset
    end
    
    properties (Access = protected)
        Cache = struct('Offset', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Offset', 'Status'} % List of non-constant message properties
        ROSPropertyList = {'offset', 'status'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = SetEndEffectorOffsetRequest(msg)
            %SetEndEffectorOffsetRequest Construct the message object SetEndEffectorOffsetRequest
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function status = get.Status(obj)
            %get.Status Get the value for property Status
            status = typecast(int16(obj.JavaMessage.getStatus), 'uint16');
        end
        
        function set.Status(obj, status)
            %set.Status Set the value for property Status
            validateattributes(status, {'numeric'}, {'nonempty', 'scalar'}, 'SetEndEffectorOffsetRequest', 'Status');
            
            obj.JavaMessage.setStatus(status);
        end
        
        function offset = get.Offset(obj)
            %get.Offset Get the value for property Offset
            if isempty(obj.Cache.Offset)
                obj.Cache.Offset = feval(obj.GeometryMsgsVector3Class, obj.JavaMessage.getOffset);
            end
            offset = obj.Cache.Offset;
        end
        
        function set.Offset(obj, offset)
            %set.Offset Set the value for property Offset
            validateattributes(offset, {obj.GeometryMsgsVector3Class}, {'nonempty', 'scalar'}, 'SetEndEffectorOffsetRequest', 'Offset');
            
            obj.JavaMessage.setOffset(offset.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Offset)
                obj.Cache.Offset.setJavaObject(offset.getJavaObject);
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Offset = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Status = obj.Status;
            
            % Recursively copy compound properties
            cpObj.Offset = copy(obj.Offset);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Status = strObj.Status;
            obj.Offset = feval([obj.GeometryMsgsVector3Class '.loadobj'], strObj.Offset);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Status = obj.Status;
            strObj.Offset = saveobj(obj.Offset);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.kinova_msgs.SetEndEffectorOffsetRequest.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.kinova_msgs.SetEndEffectorOffsetRequest;
            obj.reload(strObj);
        end
    end
end
