classdef SetFingersPositionResult < robotics.ros.Message
    %SetFingersPositionResult MATLAB implementation of kinova_msgs/SetFingersPositionResult
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2019 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'kinova_msgs/SetFingersPositionResult' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'bdbf88b45be6ef8cd65f0b4fc487d49d' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        KinovaMsgsFingerPositionClass = robotics.ros.msg.internal.MessageFactory.getClassForType('kinova_msgs/FingerPosition') % Dispatch to MATLAB class for message type kinova_msgs/FingerPosition
    end
    
    properties (Dependent)
        Fingers
    end
    
    properties (Access = protected)
        Cache = struct('Fingers', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Fingers'} % List of non-constant message properties
        ROSPropertyList = {'fingers'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = SetFingersPositionResult(msg)
            %SetFingersPositionResult Construct the message object SetFingersPositionResult
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function fingers = get.Fingers(obj)
            %get.Fingers Get the value for property Fingers
            if isempty(obj.Cache.Fingers)
                obj.Cache.Fingers = feval(obj.KinovaMsgsFingerPositionClass, obj.JavaMessage.getFingers);
            end
            fingers = obj.Cache.Fingers;
        end
        
        function set.Fingers(obj, fingers)
            %set.Fingers Set the value for property Fingers
            validateattributes(fingers, {obj.KinovaMsgsFingerPositionClass}, {'nonempty', 'scalar'}, 'SetFingersPositionResult', 'Fingers');
            
            obj.JavaMessage.setFingers(fingers.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Fingers)
                obj.Cache.Fingers.setJavaObject(fingers.getJavaObject);
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Fingers = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Recursively copy compound properties
            cpObj.Fingers = copy(obj.Fingers);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Fingers = feval([obj.KinovaMsgsFingerPositionClass '.loadobj'], strObj.Fingers);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Fingers = saveobj(obj.Fingers);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.kinova_msgs.SetFingersPositionResult.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.kinova_msgs.SetFingersPositionResult;
            obj.reload(strObj);
        end
    end
end
