j2n6s300:

  joint_state_controller:
    publish_rate: 50
    type: joint_state_controller/JointStateController

  arm:
    type: position_controllers/JointTrajectoryController
    joints:
      - j2n6s300_joint_1
      - j2n6s300_joint_2
      - j2n6s300_joint_3
      - j2n6s300_joint_4
      - j2n6s300_joint_5
      - j2n6s300_joint_6

    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      j2n6s300_joint_1: {trajectory: 0.1, goal: 0.1}
      j2n6s300_joint_2: {trajectory: 0.1, goal: 0.1}
      j2n6s300_joint_3: {trajectory: 0.1, goal: 0.1}
      j2n6s300_joint_4: {trajectory: 0.1, goal: 0.1}
      j2n6s300_joint_5: {trajectory: 0.1, goal: 0.1}
      j2n6s300_joint_6: {trajectory: 0.1, goal: 0.1}

    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10


      
  gripper:
    type: position_controllers/JointTrajectoryController
    
    constraints:
      goal_time: 1.0
      j2n6s300_joint_finger_1:
        goal: 0.02
        trajectory: 0.05
      j2n6s300_joint_finger_2:
        goal: 0.02
        trajectory: 0.05
      j2n6s300_joint_finger_3:
        goal: 0.02
        trajectory: 0.05
      stopped_velocity_tolerance: 0.02

    gains:
      j2n6s300_joint_finger_1:
        d: 0
        i: 0
        i_clamp: 1
        p: 1
      j2n6s300_joint_finger_2:
        d: 0
        i: 0
        i_clamp: 1
        p: 1
      j2n6s300_joint_finger_3:
        d: 0
        i: 0
        i_clamp: 1
        p: 1
    joints:
      - j2n6s300_joint_finger_1
      - j2n6s300_joint_finger_2
      - j2n6s300_joint_finger_3

  finger_1_position_controller:
    joint: j2n6s300_joint_finger_1
    pid:
      d: 0
      i: 0
      p: 10
    type: effort_controllers/JointPositionController
  finger_2_position_controller:
    joint: j2n6s300_joint_finger_2
    pid:
      d: 0
      i: 0
      p: 10
    type: effort_controllers/JointPositionController
  finger_3_position_controller:
    joint: j2n6s300_joint_finger_3
    pid:
      d: 0
      i: 0
      p: 10
    type: effort_controllers/JointPositionController
  finger_tip_1_position_controller:
    joint: j2n6s300_joint_finger_tip_1
    pid:
      d: 0
      i: 0
      p: 0.5
    type: effort_controllers/JointPositionController
  finger_tip_2_position_controller:
    joint: j2n6s300_joint_finger_tip_2
    pid:
      d: 0
      i: 0
      p: 0.5
    type: effort_controllers/JointPositionController
  finger_tip_3_position_controller:
    joint: j2n6s300_joint_finger_tip_3
    pid:
      d: 0
      i: 0
      p: 0.5
    type: effort_controllers/JointPositionController



# namespace is related with gazebo launch file. If the launch file does not specify the namespace,
# we do not need to add j2n6s300
# j2n6s300:
  # read joints of the robot and publish them. let the moveit know where the robot is and if it is 
  # reaching the destation