# for depth image
# sensors:
#   - sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
#     image_topic: /camera/depth/image_rect_raw
#     queue_size: 5
#     near_clipping_plane_distance: 0.15
#     far_clipping_plane_distance: 0.70
#     shadow_threshold: 0.2
#     padding_scale: 4.0
#     padding_offset: 0.03
#     max_update_rate: 2.0
#     filtered_cloud_topic: filtered_cloud

# for pointcloud
sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /camera/depth/color/points
    max_range: 1.0
    point_subsample: 1
    padding_offset: 0.1
    padding_scale: 1.0
    max_update_rate: 1.0
    filtered_cloud_topic: filtered_cloud