# from Ruijie
# controller_list:
#   - name: summit_xl/kinova_arm_controller
#     action_ns: follow_joint_trajectory
#     type: FollowJointTrajectory
#     default: true
#     joints:
#       - j2n6s300_joint_1
#       - j2n6s300_joint_2
#       - j2n6s300_joint_3
#       - j2n6s300_joint_4
#       - j2n6s300_joint_5
#       - j2n6s300_joint_6
#   - name: summit_xl/gripper
#     action_ns: gripper_command
#     type: GripperCommand
#     default: true    
#     joints:
#       - j2n6s300_joint_finger_1
#       - j2n6s300_joint_finger_2
#       - j2n6s300_joint_finger_3

# from kinova control
# controller_list:
#   - name: j2n6s300/effort_joint_trajectory_controller
#     action_ns: follow_joint_trajectory
#     type: FollowJointTrajectory
#     default: true
#     joints:
#       - j2n6s300_joint_1
#       - j2n6s300_joint_2
#       - j2n6s300_joint_3
#       - j2n6s300_joint_4
#       - j2n6s300_joint_5
#       - j2n6s300_joint_6
#   - name: j2n6s300/effort_finger_trajectory_controller
#     action_ns: follow_joint_trajectory
#     type: FollowJointTrajectory
#     default: true    
#     joints:
#       - j2n6s300_joint_finger_1
#       - j2n6s300_joint_finger_2
#       - j2n6s300_joint_finger_3

# from kinova moveit controller list
# controller_list:
#   - name: j2n6s300
#     action_ns: follow_joint_trajectory
#     type: FollowJointTrajectory
#     default: true
#     joints:
#       - j2n6s300_joint_1
#       - j2n6s300_joint_2
#       - j2n6s300_joint_3
#       - j2n6s300_joint_4
#       - j2n6s300_joint_5
#       - j2n6s300_joint_6
#   - name: j2n6s300_gripper
#     action_ns: gripper_command
#     type: GripperCommand
#     default: true    
#     joints:
#       - j2n6s300_joint_finger_1
#       - j2n6s300_joint_finger_2
#       - j2n6s300_joint_finger_3

# from openmanuator project
controller_list:
  - name: "arm"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints: [j2n6s300_joint_1, j2n6s300_joint_2, j2n6s300_joint_3, j2n6s300_joint_4, j2n6s300_joint_5, j2n6s300_joint_6]
