# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: kinova_arm
  joint_model_group_pose: arm_home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - j2n6s300_joint_1
    - j2n6s300_joint_2
    - j2n6s300_joint_3
    - j2n6s300_joint_4
    - j2n6s300_joint_5
    - j2n6s300_joint_6
    - j2n6s300_joint_finger_1
    - j2n6s300_joint_finger_tip_1
    - j2n6s300_joint_finger_2
    - j2n6s300_joint_finger_tip_2
    - j2n6s300_joint_finger_3
    - j2n6s300_joint_finger_tip_3
    - summit_back_left_wheel_joint
    - summit_back_right_wheel_joint
    - summit_front_left_wheel_joint
    - summit_front_right_wheel_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
arm_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - j2n6s300_joint_1
    - j2n6s300_joint_2
    - j2n6s300_joint_3
    - j2n6s300_joint_4
    - j2n6s300_joint_5
    - j2n6s300_joint_6
  gains:
    j2n6s300_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j2n6s300_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j2n6s300_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j2n6s300_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j2n6s300_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j2n6s300_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1